{% set name = "ticlib" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ticlib-{{ version }}.tar.gz
  sha256: 3ebdbee27629992d46d0fb0feb18dc51e790363b35b174c87de00ce5f6ed7419

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - ticlib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jphalip/ticlib
  summary: Python library to drive Pololu Tic stepper motor controllers
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jjerphan
